FROM mysql:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=my_database
ENV MYSQL_USER=my_user
ENV MYSQL_PASSWORD=my_password

# Copy initialization SQL script
COPY initi.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3306
