version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:80"  # This maps port 8083 on the host to port 80 in the container
    volumes:
      - ./src:/var/www/html:rw
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_DATABASE: my_database

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3307:3306"  # This maps port 3307 on the host to port 3306 in the container

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8084:80"  # This maps port 8084 on the host to port 80 in the container
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
